CREATE TABLE [EVENT]
(
 [ID_EVENT] int IDENTITY (1, 1) NOT NULL ,
 [NAME]     varchar(50) NOT NULL ,


 CONSTRAINT [PK_event] PRIMARY KEY CLUSTERED ([ID_EVENT] ASC)
);
GO

CREATE TABLE [TECNICO_ARL]
(
 [ID_TECNICO_ARL] int IDENTITY (1, 1) NOT NULL ,
 [NOMBRE]         varchar(50) NOT NULL ,
 [APELLIDO]       varchar(50) NOT NULL ,
 [CARGO]          varchar(50) NOT NULL ,


 CONSTRAINT [PK_tecnico_arl] PRIMARY KEY CLUSTERED ([ID_TECNICO_ARL] ASC)
);
}
GO

CREATE TABLE [REQUEST]
(
 [ID_REQUEST] int IDENTITY (1, 1) NOT NULL ,
 [TITLE]      varchar(180) NOT NULL ,
 [BODY]       text NOT NULL ,
 [FOSTER]     varchar(50) NOT NULL ,


 CONSTRAINT [PK_requerimiento] PRIMARY KEY CLUSTERED ([ID_REQUEST] ASC)
);
GO

CREATE TABLE [HISTORY]
(
 [ID_HISTORY]     int NOT NULL ,
 [CREATE_DATE]    date NOT NULL ,
 [ID_EVENT]       int NOT NULL ,
 [EVENT_MESSAGE]  text NOT NULL ,
 [ID_REQUEST]     int NOT NULL ,
 [ID_TECNICO_ARL] int NOT NULL ,


 CONSTRAINT [PK_history] PRIMARY KEY CLUSTERED ([ID_HISTORY] ASC),
 CONSTRAINT [FK_14] FOREIGN KEY ([ID_REQUEST])  REFERENCES [REQUEST]([ID_REQUEST]),
 CONSTRAINT [FK_35] FOREIGN KEY ([ID_TECNICO_ARL])  REFERENCES [TECNICO_ARL]([ID_TECNICO_ARL]),
 CONSTRAINT [FK_43] FOREIGN KEY ([ID_EVENT])  REFERENCES [EVENT]([ID_EVENT])
);
GO


CREATE NONCLUSTERED INDEX [fkIdx_14] ON [HISTORY] 
 (
  [ID_REQUEST] ASC
 )

GO

CREATE NONCLUSTERED INDEX [fkIdx_35] ON [HISTORY] 
 (
  [ID_TECNICO_ARL] ASC
 )

GO

CREATE NONCLUSTERED INDEX [fkIdx_43] ON [HISTORY] 
 (
  [ID_EVENT] ASC
 )

GO

CREATE TABLE [FORO]
(
 [ID_FORO]     int IDENTITY (1, 1) NOT NULL ,
 [TITLE]       varchar(100) NOT NULL ,
 [DESCRIPCION] text NOT NULL ,
 [ID_REQUEST]  int NOT NULL ,


 CONSTRAINT [PK_foro] PRIMARY KEY CLUSTERED ([ID_FORO] ASC),
 CONSTRAINT [FK_70] FOREIGN KEY ([ID_REQUEST])  REFERENCES [REQUEST]([ID_REQUEST])
);
GO


CREATE NONCLUSTERED INDEX [fkIdx_70] ON [FORO] 
 (
  [ID_REQUEST] ASC
 )

GO

CREATE TABLE [MENSAJE]
(
 [ID_MENSAJE]     int  NOT NULL ,
 [BODY]           text NOT NULL ,
 [ID_FORO]        int NOT NULL ,
 [ID_TECNICO_ARL] int NOT NULL ,


 CONSTRAINT [PK_mensaje] PRIMARY KEY CLUSTERED ([ID_MENSAJE] ASC),
 CONSTRAINT [FK_63] FOREIGN KEY ([ID_FORO])  REFERENCES [FORO]([ID_FORO]),
 CONSTRAINT [FK_73] FOREIGN KEY ([ID_TECNICO_ARL])  REFERENCES [TECNICO_ARL]([ID_TECNICO_ARL])
);
GO


CREATE NONCLUSTERED INDEX [fkIdx_63] ON [MENSAJE] 
 (
  [ID_FORO] ASC
 )

GO

CREATE NONCLUSTERED INDEX [fkIdx_73] ON [MENSAJE] 
 (
  [ID_TECNICO_ARL] ASC
 )

GO
